informatics learning languages cycles
userINF500/lessons pull request #3
Opened 2023-12-01 20:31 UTC by userINF500

добавил дз по циклам вайл и фор

2023-12-02 10:14 UTC, justas05 requested changes
Название файла немного странное...

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +void sum_of_squares ()
После имени функции пробел не нужен

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +#include <stdio.h>
После заголовочников делай отступ в 1 строку

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    for(i = 1; i<=n; i++)
`for (i = 1; i <= n; i++)`

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    result=1;
пробелы

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    for (i=1; i<=N; i++)
пробелы

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    for (i =1; i<=N; i++)
пробелы

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +void degree ()
лишний пробел

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    result =1;
пробелы

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +        result = result * 2;
Можно использовать сокращенную операцию `res *= 2;`

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    result =1;
пробелы

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    for (i = 1; i<=n; i++)
пробелы

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +        result = result*n;
пробелы

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +}
В конце оставляй пустую строку для корректного отображения

2023-12-02 10:14 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +        printf("%d", i*i);
пробелы

2023-12-08 19:41 UTC, userINF500 commented on informaics/learning laguages/cyclec.c
> +void sum_of_squares ()
название такое потому что это перевод слова циклы на английский

2023-12-08 19:41 UTC, userINF500 commented on informaics/learning laguages/cyclec.c
> +void sum_of_squares ()
я про название файла

2023-12-09 07:30 UTC, justas05 requested changes

2023-12-09 07:30 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +    result=1;
Здесь по-прежнему нужны пробелы

2023-12-09 07:30 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +        result = result*n;
Так же

2023-12-09 07:30 UTC, justas05 commented on informaics/learning laguages/cyclec.c
>          i = i + 1;
Здесь лучше использовать инкремент

2024-01-05 07:44 UTC, justas05 approved these changes

2024-01-05 07:44 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +        i ++ ;
Здесь пробел лишний, инкремент пишется `i++;`

2024-01-05 07:44 UTC, justas05 commented on informaics/learning laguages/cyclec.c
> +        result = result * n;
Можно использовать сокращенные операции `result *= n;`

2024-01-05 15:23 UTC, merged