Homework about binary operations
userINF500/lessons pull request #4
Opened 2023-12-22 20:10 UTC by userINF500

2023-12-23 11:02 UTC, justas05 requested changes
Все сам сделал?

2023-12-23 11:02 UTC, justas05 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num ^ (1 << (pos - 1) );
`pos - 1` не надо делать - отсчет начинается с нуля

2023-12-26 11:08 UTC, userINF500 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num ^ (1 << (pos - 1) );
просто pos оставить?

2023-12-26 11:54 UTC, justas05 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num ^ (1 << (pos - 1) );
Да, потому что программисты ведут отсчет с нуля)

2023-12-26 13:06 UTC, userINF500 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num ^ (1 << (pos - 1) );
а первый пр можно мержить?

2023-12-26 16:00 UTC, justas05 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num ^ (1 << (pos - 1) );
Если там есть мой апрув, и ты больше ничего не планируешь добавлять, то да

2023-12-28 14:05 UTC, justas05 requested changes

2023-12-28 14:05 UTC, justas05 commented on informaics/learning laguages/individual/binary_ops.c
>      printf("%d", a);
Чтобы было лучше видно значение переменной, выводи в шестнадцатиричном виде. `printf("%x\n", a);`

2023-12-28 14:05 UTC, justas05 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num | ( (1 << pos ) >> 1);
Сдвиг вправо совсем не нужен. Мы считаем от 0, поэтому просто `num | (1 << pos)`

2023-12-29 20:45 UTC, justas05 requested changes
Почему ты не решаешь следующие разделы?

2023-12-29 20:45 UTC, justas05 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num | (1 << pos );
Пробел лишний

2023-12-29 20:45 UTC, justas05 commented on informaics/learning laguages/individual/binary_ops.c
> +    printf("%x\n", a);
Это нужно было только для тебя. Если ты ручками не попробовал установить бит, то эта запись не несет смысла.

2023-12-30 07:33 UTC, userINF500 commented on informaics/learning laguages/individual/binary_ops.c
> +    return num | (1 << pos );
я начал массивы просто решил больше задач сделать перед тем как пушить

2024-01-04 18:19 UTC, userINF500 commented on informaics/learning laguages/individual/binary_ops.c
> +    printf("%x\n", a);
я в калькуляторе переводил число из десятичной формы в шестнадцатеричную и сверял побитово с результатом

2024-01-05 07:45 UTC, justas05 approved these changes

2024-01-05 15:24 UTC, merged