informatics massives
userINF500/lessons pull request #5
Opened 2023-12-30 07:49 UTC by userINF500

2023-12-30 09:26 UTC, justas05 requested changes

2023-12-30 09:26 UTC, justas05 commented on informaics/learning laguages/massives.c
> +}
В конце файла оставляй пустую строку

2023-12-30 09:26 UTC, justas05 commented on informaics/learning laguages/massives.c
> +    for( i = 0; i < N; i++)
пробелы стоят не так `for (i = 0...`

2023-12-30 09:26 UTC, justas05 commented on informaics/learning laguages/massives.c
> +void A0_A2_A4 ()
пробел здесь не нужен

2023-12-30 09:26 UTC, justas05 commented on informaics/learning laguages/massives.c
> +
лишняя пустая строка

2023-12-30 09:26 UTC, justas05 commented on informaics/learning laguages/massives.c
> +#include <math.h>
~math.h~ не нужен тут

2024-01-09 04:55 UTC, justas05 commented on informaics/learning laguages/massives.c
> +    int arr[N];
А мы уже изучили динамические массивы?

2024-01-09 04:55 UTC, justas05 commented on informaics/learning laguages/massives.c
> +    for ( k = 0; k < N; k++)
Старайся следить за пробелами

2024-01-13 07:01 UTC, justas05 requested changes

2024-01-13 07:01 UTC, justas05 commented on informaics/learning laguages/massives.c
> +    for (m = 0; m < N; m++)
Почему счетчик первого уровня назвал не `i`? Есть какая-то причина или просто так захотел?

2024-01-13 07:01 UTC, justas05 commented on informaics/learning laguages/massives.c
> +    scanf("%d", &N);
Делай отступ в одну строку после объявления переменных

2024-01-13 07:01 UTC, justas05 commented on informaics/learning laguages/massives.c
> +            k += 1;
Используй сишный инкремент - `++i или i++`

2024-01-13 07:56 UTC, userINF500 commented on informaics/learning laguages/massives.c
> +    for (m = 0; m < N; m++)
просто захотел

2024-01-15 06:52 UTC, justas05 commented on informaics/learning laguages/massives.c
> +    for (m = 0; m < N; m++)
Под счетчики используют `i, j, k` - это негласное правило

2024-01-20 10:20 UTC, justas05 reviewed
Это же промежуточная версия?

2024-01-20 14:44 UTC, userINF500 commented
> Это же промежуточная версия?

да

2024-01-27 09:56 UTC, justas05 approved these changes

2024-02-03 07:41 UTC, merged